### ISSUE TITLE
not work to two PC

### ISSUE THREAD

**Issue by s-kobets** [lekzd/script_battle_game#3]
PC1: run localhost:8080 and :1337
PC2: ssh -L for transfer port 8080 from PC1

PC1: create new room
PC2: enter href left or right room not working

Error: this.game = undefined in class BattleGame

**Comment by lekzd** [comment]
@s-kobets localhost:8080 это только для локальной разработки, для собственного сервера советую сразу запускать в собранный бандл и сервер. Возможно тут проблемы webpack-dev-server, который что-то не дослал на фронт другого компа

**Comment by s-kobets** [comment]
@lekzd  не работает команда `build`
<img width="468" alt="2018-12-04 23 58 47" src="https://user-images.githubusercontent.com/13196034/49472501-a7a43a80-f820-11e8-9480-7dda9b4cdeeb.png">
node version: 10.13, так же попробовал на 9.9

**Comment by lekzd** [comment]
@s-kobets нужно больше данных, по имеющимся сложно сказать что именно случилось
попробуй хоть плагины поотключать из webpack конфига (у меня на маке и windows такой ошибки не наблюдается)

**Comment by s-kobets** [comment]
@lekzd `webpack-closure-compiler` выдавал эту ошибку.
