### ISSUE TITLE
Hello from HelsinkiJS

### ISSUE THREAD

**Issue by sarukuku** [lekzd/script_battle_game#4]
Hi! I think you submitted a talk to HelsinkiJS meetup a while back. I wasn't able to contact you via the email address passed to me via Meetabit and couldn't find any other contact info for you so I'm opening an issue to ask if you could drop me an email to joonas.salovaara@gmail.com so that we can continue our discussion. Thanks! 😄

**Comment by lekzd** [comment]
@sarukuku ping you via email
