### ISSUE TITLE
WebPack ошибка

### ISSUE THREAD

**Issue by goblin193p** [lekzd/script_battle_game#5]
WebPack 4.29.3
Node 8.12.0
NPM 6.4.1
Win 10
Команда WebPack выдаёт ошибку, 
![webpack_error](https://user-images.githubusercontent.com/5001648/52804979-9c7a5000-3096-11e9-9717-3323b220a14b.jpg)

**Comment by s-kobets** [comment]
@ts-ignore тебе в помощь

**Comment by goblin193p** [comment]
Респект **[s-kobets](/s-kobets) **, работает!
